Jenkinsfile_CNP
bin/import-bpmn-diagram.sh

All `-nonprod.json` files are now excluded on staging and preview to ensure we deploy and test production version of CCD definition.
```
[ ] Yes
[x] No
```

build: excluded -nonprod.json files from definition on preview and staging

---

bin/pull-latest-release-asset.sh

https://tools.hmcts.net/jira/browse/CMC-1688
The fix for this was changed when it was found that the reason the script fails was because the GitHub API calls were being rate limited
`{"message":"API rate limit exceeded for 20.50.109.148. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`
Adding an authentication token to the API call increases the rate limit
```
[ ] Yes
[x] No
```

fix: Add authentication to pull-latest-release-asset.sh (CMC-1688)

---

src/main/resources/camunda/create_sdo.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateSDOTest.java

https://tools.hmcts.net/jira/browse/CIV-863
This PR create a Camunda diagram for the CREATE_SDO journey. This is just a basic diagram which will be added to later, for now we just want to send emails to related parties once an SDO has been triggered on a case.
```
[ ] Yes
[x] No
```

create sdo camunda diagram

---

src/main/resources/camunda/initiate_general_application.bpmn

https://tools.hmcts.net/jira/browse/CIV-206
1. Modify the camunda flow to have the case event as ASSIGN_GA_ROLES and description as Assigning of GA roles.
2. Create an event (ASSIGN_GA_ROLES) with about to submit call back in General App ccd definition 
3. Create a Call back Handler for the above. 
4. Extract the parent case id from the general application data 
5. Do a GET call to get the parent case.
6. Get the solicitors details (applicant and defendant) 
7. Use the CCD Api of assigning roles to assign the correct role to the solicitor. 
Modify the camunda flow to have the case event as ASSIGN_GA_ROLES and description as Assigning of GA roles.
Civil Service- …

CIV-206 Refactor Assign GA role task

---

charts/civil-camunda/Chart.yaml

- Bump java charts to v3.7.2
- Bump camunda-bpm to 0.0.23
N/A
```
[ ] Yes
[x] No
```

build/bump-charts: Update java charts to v3.7.2

---

build.gradle

Code coverage is more in Api tests than ui tests and ui screens are not affected by camunda changes. Only events testing should be sufficient
[Civil - Unspec Api coverage.xlsx](https://github.com/hmcts/civil-camunda-bpmn-definition/files/8162144/Civil.-.Unspec.Api.coverage.xlsx)

Slim functional tests - Run only Api tests

---

build.gradle

This PR will add the `jackson-databind` dependency. This is to address a CVE that was identified in PR-154: https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_Civil%2Fcivil-camunda-bpmn-definition/detail/PR-154/2/pipeline/
```
[ ] Yes
[x] No
```

add jackson databind dependency to address cve

---

config/owasp/suppressions.xml
src/main/resources/camunda/inform_agreed_extension_date.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/InformAgreedExtensionDateTest.java

https://tools.hmcts.net/jira/browse/CMC-1961
Implemented notifying respondent 2 solicitor about time extension for a 1v2 different solicitor scenario
```
[ ] Yes
[X] No
```

Notifying respondent 2 solicitor about time extension

---

src/main/resources/camunda/claim_dismissed.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimDismissedTest.java

https://tools.hmcts.net/jira/browse/CMC-1354
Change to include respondent solicitor 2 notification in Case dismissed
- Update of https://github.com/hmcts/civil-camunda-bpmn-definition/pull/149/commits with tests
```
[ ] Yes
[x] No
```

feat/CMC-1354: adding notification for respondent 2 in claim dismissed

---

src/main/resources/camunda/create_sdo.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateSDOTest.java

https://tools.hmcts.net/jira/browse/CIV-1376
This PR edits the `CREATE_SDO` Camunda diagram to handle multiparty emails.
There applicants task was edited to be plural since for the applicants (1 or 2) only 1 email will be sent as they both have the same legal rep.
For the defendants (1 or 2) there is a possibility of two different legal reps so a second notification task for defendant solicitor 2 was created.
```
[ ] Yes
[x] No
```

update create_sdo diagram

---

config/owasp/suppressions.xml
src/main/resources/camunda/take_case_offline.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/TakeCaseOfflineTest.java

https://tools.hmcts.net/jira/browse/CMC-2033
- Added  notify respondent 2 solicitors task to TAKE_CASE_OFFLINE process.
```
[ ] Yes
[X] No
```

Case Taken Offline Schedular enhanced to cater for multiparty 1 v 2

---

bin/add-roles.sh

https://tools.hmcts.net/jira/browse/CIV-1859
This PR updates the `add-roles.sh` to include the newly created `legal-adviser` role.
This PR is to be merged in after it's [ccd counterpart](https://github.com/hmcts/civil-ccd-definition/pull/1043) has been merged in.
```
[ ] Yes
[x] No
```

update add roles script

---

config/owasp/suppressions.xml
src/main/resources/camunda/claim_dismissed.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimDismissedTest.java

https://tools.hmcts.net/jira/browse/CIV-4632
Moving the notify RPA event just after notifying applicant solicitor 1 to send an email to RPA when a claim is dismissed .
```
[ ] Yes
[ ] No
```

CIV-4632: camunda change

---

config/owasp/suppressions.xml
src/main/resources/camunda/claim_dismissed.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimDismissedTest.java

https://tools.hmcts.net/jira/browse/CIV-4632
Moving the notify RPA event just after notifying applicant solicitor 1 to send an email to RPA when a claim is dismissed .
```
[ ] Yes
[ ] No
```

CIV-4632 - Claim dismissal after notify claim 

---

.github/workflows/stale.yml

Added a github flow for stale PRs which will mark PRs as stale after 7 days of inactivity and close them
```
[ ] Yes
[ x] No
```

adding stale config for stale pr

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CIV-4838
In JetBrains Kotlin before 1.6.0, it was not possible to lock dependencies for Multiplatform Gradle Projects.
```
[ ] Yes
[ ] No
```

CIV-4838: Fix for CVE-2022-24329

---

src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java

https://tools.hmcts.net/jira/browse/CIV-3523
- Moving scheduler to trigger out of release hours (03:00) from 00:05
- This will then be reverted as a post release activity
Useful Notes:
https://docs.camunda.org/javadoc/camunda-bpm-platform/7.3/org/camunda/bpm/engine/impl/calendar/CronExpression.html
```
[ ] Yes
[x] No
```

DO NOT MERGE - release: postpone clam deadline scheduler to 3am

---

src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java

https://tools.hmcts.net/jira/browse/CIV-3523
- Moving scheduler to trigger out of release hours (03:00) from 00:05
- This will then be reverted as a post release activity
Useful Notes:
https://docs.camunda.org/javadoc/camunda-bpm-platform/7.3/org/camunda/bpm/engine/impl/calendar/CronExpression.html
```
[ ] Yes
[x] No
```

release: postpone clam deadline scheduler to 3am

---

src/main/resources/camunda/case_proceeds_in_caseman.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/CaseProceedsInCasemanTest.java

https://tools.hmcts.net/jira/browse/CIV-6413
Modified case_proceeds_in_caseman and added logic for not informing unrepresented defendant1. Two new conditions added for logic
Added following conditions to bpm
- For informing represented defendandt : 
${empty flowFlags.UNREPRESENTED_DEFENDANT_ONE  || (!empty flowFlags.UNREPRESENTED_DEFENDANT_ONE && !flowFlags.UNREPRESENTED_DEFENDANT_ONE)}
- For continue flow without informing defendant1: 
${!empty flowFlags.UNREPRESENTED_DEFENDANT_ONE && flowFlags.UNREPRESENTED_DEFENDANT_ONE}
```
[ ] Yes
[ ] No
```

CIV-6413: Added logic for not notifying unrepresented defendant1

---

Jenkinsfile_CNP

CIV-6644
- Always clears the pods regardless of success or failure
- Bonus: Observes "enableHelm" label to prevent deletion of pods on success if so desired
```
[ ] Yes
[x] No
```

CIV-6644 Clear pods always and enableHelm

---

src/main/resources/camunda/breathing_space_lifted.bpmn
src/main/resources/camunda/inform_agreed_extension_date.bpmn

https://tools.hmcts.net/jira/browse/CIV-6479
added default flow to camunda where no default was present to resolve warning in logs.
```
Exclusive Gateway 'RPA_Continuous_Feed_Gate' has outgoing sequence flow 'FLOW_WITHOUT_DEFAULT' without condition which is not the default flow. We assume it to be the default flow, but it is bad modeling practice, better set the default flow in your gateway. | resource FILE_WARNING_PRESENT_IN
```
the files warning present in changed in this PR is: `inform_agreed_extension_date.bpmn` and `breathing_space_lifted.bpmn`
```
[ ] Yes
[x] No
```

CIV-6479 - added default flow to camunda

---

src/main/resources/camunda/defendant_response_cui.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java

https://tools.hmcts.net/jira/browse/CIV-8122
- Template defendant response submission in welsh when bilingual response.
- Changes in camunda flow : The defendant is always notified of the response, the applicant is only notified if it iis NOT bilingual (if it is bilingual, it is notified after uploading the translated documents).
```
[ ] Yes
[X] No
```

CIV-8122 - Defendant Submission Notification -  Welsh

---

config/owasp/suppressions.xml
src/main/resources/camunda/polling_event_emitter_scheduler.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java

We have this P2 incident where poller is constantly rerunning the events and it causing all the claims stuck and issues for users.

CIV-0000 Stopping poller for the weekend

---

src/main/resources/camunda/defendant_response_cui.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java

https://tools.hmcts.net/jira/browse/CIV-9806
updated Respond to Claim CUI camunda flow when response language is Bilingual.
```
[ ] Yes
[x] No
```

CIV-9806 - Generate Defendant Response PDF and DQs when Welsh has been selected

---

Dockerfile
build.gradle
config/checkstyle/checkstyle.xml
gradle/wrapper/gradle-wrapper.properties

We have noticed deprecated configuration in HMCTS_a_to_c/civil-camunda-bpmn-definition
Please upgrade to Java 17
This configuration will stop working by 01/08/2023
```
[ ] Yes
[ ] No
```

CIV-9929  Upgrade Java and gradle

---

src/main/resources/camunda/apply_noc_decision_lip.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionLipTest.java

https://tools.hmcts.net/jira/browse/CIV-11523
Revoking access to claim for claimant LiP after NoC and and representative assigned
```
[ ] Yes
[x] No
```

CIV-11523 Revoking access to claim for claimant LiP after NoC and and representative assigned

---

src/main/resources/camunda/spec-automated-hearing-notice-scheduler.bpmn
src/main/resources/camunda/unspec-automated-hearing-notice-scheduler.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/SpecAutomatedHearingNoticeSchedulerTest.java
src/test/java/uk/gov/hmcts/reform/civil/bpmn/UnspecAutomatedHearingNoticeSchedulerTest.java

https://tools.hmcts.net/jira/browse/CIV-12997
- Update timer from 30s to 5 mins before calling unnotified again
- Giving more time for camunda processes to finish before making an expensive request to HMC
```
[ ] Yes
[x] No
```

CIV-12997 - Update AHN burndown timers

---

src/main/resources/camunda/defendant_response_deadline_check_scheduler.bpmn
src/main/resources/camunda/full_admit_pay_immediately_no_payment_scheduler.bpmn
src/main/resources/camunda/settlement_no_defendant_response_scheduler.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseDeadlineCheckSchedulerTest.java
src/test/java/uk/gov/hmcts/reform/civil/bpmn/FullAdmitPayImmediatelyNoPaymentSchedulerTest.java
src/test/java/uk/gov/hmcts/reform/civil/bpmn/SettlementNoResponseFromDefendantSchedulerTest.java

Dashboard schedulers delayed to 2026, so they don't run in prod.
```
[ ] Yes
[x] No
```

CIV-0000 - set Dashboard schedulers to 2026

---

src/main/resources/camunda/defendant_response_spec.bpmn

https://tools.hmcts.net/jira/browse/CIV-13622
Add claimant dashboard task generation in defendant response spec when the claimant is lip and the dashboard feature toggle is active.
```
[ ] Yes
[X] No
```

CIV-13622 Defendant Response Spec - Claimant Dashboard Tasks

---

src/main/resources/camunda/notify_set_aside_judgment_request.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifySetAsideJudgmentTest.java

[CIV-13752](https://tools.hmcts.net/jira/browse/CIV-13752)
Claimant LiP dashboard notifications: set aside after court error
```
[ ] Yes
[x] No
```

CIV-13752 Claimant LiP dashboard notifications: set aside after court error

---

src/main/resources/camunda/notify_set_aside_judgment_request.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifySetAsideJudgmentTest.java

[Defendant LiP dashboard notifications: set aside after court error](https://tools.hmcts.net/jira/browse/CIV-13753)
Default Judgment set aside by caseworker after being recorded in error. Dashboard notification is displayed to inform the Defendant that a judgment made in error against them has been set aside.
```
[ ] Yes
[X ] No
```

CIV-13753 Set Aside Error DashboardNotification LIP

---

src/main/resources/camunda/amend_restitch_bundle.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/AmendRestitchBundleTest.java

Reverts hmcts/civil-camunda-bpmn-definition#1059
Due to issue where async return of document does not work even if timer is put before business process:

CIV-14748 - Revert "CIV-14748 Add 5 Minutes Delay Before Notifications"

---

src/main/resources/camunda/case_proceeds_in_caseman.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/CaseProceedsInCasemanTest.java

https://tools.hmcts.net/jira/browse/CIV-15835
Swap the position of main case dashboard notification tasks because As the case moves offline "Dashboard notification for claimant1/defendant" task handler deletes all the notifications associated with the case which in turn deletes the GA application moved offline notification too.
Old Camunda 
New Camunda
```
[ ] Yes
[x] No
```

CIV-15835 - 'Application is offline' dashboard notification not shown to applicant

---

src/main/resources/camunda/set_aside_judgment_request.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/SetAsideJudgmentTest.java

https://tools.hmcts.net/jira/browse/CIV-15767
Set Aside Add RPA Live Feed
Flow_JO_LIVE_FEED_DISABLED - ${empty flowFlags.IS_JO_LIVE_FEED_ACTIVE || !flowFlags.IS_JO_LIVE_FEED_ACTIVE}
Flow_JO_LIVE_FEED_ENABLED - ${!empty flowFlags.IS_JO_LIVE_FEED_ACTIVE && flowFlags.IS_JO_LIVE_FEED_ACTIVE}
```
[ ] Yes
[X ] No
```

CIV-15767 Set Aside Add RPA Live Feed

---

src/main/resources/camunda/initiate_general_application.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java

https://tools.hmcts.net/jira/browse/CIV-16361
Send respondent notification if free application
```
[ ] Yes
[x] No
```

CIV-16361 Send respondent notification if free application

---

src/main/resources/camunda/defendant_response_spec.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseSpecTest.java

https://tools.hmcts.net/jira/browse/CIV-16999
Added a task to update the GA status when main claims move offline.
```
[ ] Yes
[x] No
```

CIV-16999 - GA activity still available after claim moves offline when in state - Awaiting Further Information

---

src/main/resources/camunda/claimant_response_cui.bpmn
src/main/resources/camunda/upload_translated_document_claimant_rejects_repayment_plan.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantsRejectsRepaymentPlanDocumentTest.java

https://tools.hmcts.net/jira/browse/CIV-16867
When a claimant rejects the repayment plan and the mail claim involves a Welsh party, the modified claimant intention flow will pause the notification.
Added new camunda to resume the paused task after WLU uploads the translated document.
```
[ ] Yes
[x] No
```

CIV-16867 - Delay notifications and visibility of Manual Determination document (includes show element)

---

src/main/resources/camunda/defendant_response_cui.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java

https://tools.hmcts.net/jira/browse/DTSCCI-2315
Change defendant_response_cui.bpmn to use NOTIFY_EVENT to notify all parties in one event
**Before**
**After**
Dependant on: https://github.com/hmcts/civil-service/pull/6672
```
[ ] Yes
[ ] No
```

DTSCCI-2315 Change defendant_response_cui.bpmn to use NOTIFY_EVENT to notify all parties in one event

---

src/main/resources/camunda/apply_noc_decision_defendant_lip.bpmn
src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionDefendantLipTest.java

https://tools.hmcts.net/jira/browse/CIV-17589
Updated the Defendant liP NOC flow to modify the GA task status when the main case transitions to offline
```
[ ] Yes
[x] No
```

CIV-17589 - GA not moving offline when Main Claim moves offline post NoC

---

src/main/resources/camunda/open_incident_retry_scheduler.bpmn

https://tools.hmcts.net/jira/browse/DTSCCI-2645
As part of this scheduler by default it will take all open incidents within last 24hrs and retry at 11pm every day.
But if we are triggering it manually we can use below fields to filter the incidents more precisely
incidentStartTime "2025-09-17T15:20:05.471+0000"
incidentEndTime  "2025-09-17T16:20:05.471+0000"
incidentMessageLike %502%

DTSCCI-2645 Add incident retry scheduler
