hmcts/civil-camunda-bpmn-definition

Jenkinsfile_CNP, audit.json, bin/import-bpmn-diagram.sh, bin/import-ccd-definition.sh, build.gradle, charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml, charts/civil-camunda/values.yaml, src/test/java/uk/gov/hmcts/reform/civil/bpmn/AcknowledgeClaimTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CaseDismissedSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DismissClaimTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDetailsTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ResetRpaNotifyBusinessProcessTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RetryRpaNotificationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TakeCaseOfflineSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TakeCaseOfflineTest.java
https://tools.hmcts.net/jira/browse/CMC-1541
```
[x] Yes
[ ] No
```
=> feat: renamed unspec to civil (CMC-1541)

src/main/resources/camunda/case_proceeds_in_caseman.bpmn, src/main/resources/camunda/claim_dismissed_scheduler.bpmn, src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn, src/main/resources/camunda/polling_event_emitter_scheduler.bpmn, src/main/resources/camunda/take_case_offline_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CaseDismissedSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CaseProceedsInCasemanTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TakeCaseOfflineSchedulerTest.java
Merging with latest civil-damages master branch
`git remote add civil-damages git@github.com:hmcts/civil-damages-camunda-bpmn-definition.git`
`git pull civil-damages master`
=> feat: merge with latest civil-damages master

build.gradle
=> build: merged dependencies

bin/import-bpmn-diagram.sh, bin/variables/load-prod-environment-variables.sh
Reverts hmcts/civil-camunda-bpmn-definition#13
=> Revert "feat:Add tenant Id and deployment for prod"

charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml
=> build: switched to latest XUI image

bin/add-roles.sh
=> build: added staff role to env setup script

build.gradle
CMC-1682
```
[ ] Yes
[ ] No
```
=> fix:  CVE-2021-22118 (CMC-1682)

build.gradle
Covers Dependabot PRs #30, #29, #27, #26, #24
https://tools.hmcts.net/jira/browse/CMC-1684
```
[ ] Yes
[x] No
```
=> build(deps): Bump dependencies (CMC-1684)

build.gradle
[CMC-1500](url)
clean up gradle
=> tech: cleanup gradle (CMC-1500)

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CMC-1680
```
[ ] Yes
[x] No
```
=> build: added uploading camunda diagrams on demo (CMC-1680)

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CMC-1680
```
[ ] Yes
[x] No
```
=> fix: added pushing to demo from master (CMC-1680)

src/main/resources/camunda/notify_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimTest.java
[CMC-1613](https://tools.hmcts.net/jira/browse/CMC-1613)
Update notify claim camunda diagram and add RPA continuous feed.
=> feat: Update notify claim camunda diagram for RPA continuous feed (CMC-1613)

src/main/resources/camunda/notify_claim_details.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDetailsTest.java
[CMC-1614](https://tools.hmcts.net/jira/browse/CMC-1614)
Update notify claim details camunda diagram and add RPA continuous feed.
=> feat: Update notify claim details camunda diagram for RPA continuous feed (CMC-1614)

src/main/resources/camunda/acknowledge_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/AcknowledgeClaimTest.java
[CMC-1615](https://tools.hmcts.net/jira/browse/CMC-1615)
Update acknowledge claim camunda diagram for RPA continuous feed 
=> feat: Update acknowledge claim camunda diagram for RPA continuous feed (CMC-1615)

src/main/resources/camunda/defendant_response.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseTest.java
[CMC-1616](https://tools.hmcts.net/jira/browse/CMC-1616)
update full defence camunda diagram for RPA continuous feed 
=> feat: update full defence camunda diagram for RPA continuous feed (CMC-1616)

src/main/resources/camunda/add_defendant_litigation_friend.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/AddDefendantLitigationFriendTest.java
[CMC-1618](https://tools.hmcts.net/jira/browse/CMC-1618)
update add litigation friend camunda diagram for continuous feed
=> feat: update add litigation friend camunda diagram for continuous feed (CMC-1618)

charts/civil-camunda/Chart.yaml
N/A
- Bump java chart version to 3.6.0 
```
[] Yes
[x] No
```
=> build: bump java charts to 3.6.0

README.md
N/A
Regenerate Master Pipeline
```
[ ] Yes
[X] No
```
=> regenerate master pipeline

src/main/resources/camunda/create_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimTest.java
https://tools.hmcts.net/jira/browse/CMC-1827
- Updating create claim handed offline notification template to be more generic
```
[ ] Yes
[x] No
```
=> CMC-1827: Update create claim hand offline notification

src/main/resources/camunda/notify_claim_details.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDetailsTest.java
https://tools.hmcts.net/jira/browse/CMC-1646
Adding Notification to Claimant Solicitor for Handed Offline
Adding RPA Task for Handed Offline
```
[ ] Yes
[ X] No
```
=> feat/CMC-1646: Notify_Claim_Details_RPA_Handle_Offline_Task_Latest

src/main/resources/camunda/notify_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimTest.java
https://tools.hmcts.net/jira/browse/CMC-1645
- Adding Notification to Claimant Solicitor for Handed Offline
- Adding RPA Task for Handed Offline
```
[ ] Yes
[x] No
```
=> feat/CMC-1645: Notify Claim RPA Hand Offline Task + Notification

charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CCD-2269
Add am-role-assignment-service to preview-aat yml and update hmctspublic version in chart yml
```
[ x] Yes
[ ] No
```
=> Feat update helm chart

charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml
N/A
Fix Preview and master pipelines due to release by access management
```
[ ] Yes
[X] No
```
=> Chore: fix preview and master pipeline

Jenkinsfile_CNP
N/A
Fix Pipeline
```
[ ] Yes
[X] No
```
=> Chore: fix pipeline

build.gradle
N/A
Add Nightly tests to build.gradle
```
[ ] Yes
[X] No
```
=> Chore: add nightlyTests

Jenkinsfile_CNP
Free resources in preview cluster after pr turns green.
More info : https://github.com/hmcts/cnp-jenkins-library/pull/801
=> Clear helm release on successful build

src/main/resources/camunda/claim_dismissed.bpmn
Reverts hmcts/civil-camunda-bpmn-definition#149
=> Revert "Feat/cmc 1354"

src/main/resources/camunda/create_claim_spec.bpmn
https://tools.hmcts.net/jira/browse/CIV-1228
LRvLR: MP claim issuance: Camunda tasks
```
[ ] Yes
[x] No
```
=> CIV-1228 change

src/main/resources/camunda/generate_DJ_form.bpmn, src/main/resources/camunda/generate_spec_DJ_form.bpmn
https://tools.hmcts.net/jira/browse/CIV-121
```
[ ] Yes
[ X] No
```
=> CIV-121 - To generate Default Judgment claim form

config/owasp/suppressions.xml
=> CIV-121 - Suppress cve CVE-2-22-22950

Jenkinsfile_CNP
=> Do not upload ,*DJspec.json,*DJ.json

config/owasp/suppressions.xml
=> Temp fix security check

build.gradle, src/main/resources/camunda/defendant_response_spec.bpmn
Ba deploy awaits1
```
[ ] Yes
[ ] No
```
=> Ba deploy awaits1

config/owasp/suppressions.xml, src/main/resources/camunda/defendant_response_spec.bpmn
https://tools.hmcts.net/jira/browse/CIV-2465
```
[ ] Yes
[ ] No
```
=> CIV-2465: Adding Generate sealed form in defendant response

src/main/resources/camunda/initiate_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java
https://tools.hmcts.net/jira/browse/CIV-1817
Add fee validation before payment.
```
[ ] Yes
[X] No
```
=> CIV-1817 Add Fee validation in the initiate_general_application.bpmn

src/main/resources/camunda/claimant_response_spec.bpmn
Conditions changed to allow defendant responses other than full defence to pass for I2P
```
[ ] Yes
[X] No
```
=> [NO ISSUE] changed to allow full and part admission responses

src/main/resources/camunda/generate_DJ_form.bpmn
=> CIV-122 notification bpmn

build.gradle, charts/civil-camunda/Chart.yaml, config/owasp/suppressions.xml
=> upgrade and fix vulnerability

charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml
=> added lrd url for civil service

charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-3020
```
[ ] Yes
[x] No
```
=> Config for judicial ref data

src/main/resources/camunda/defendant_response_spec.bpmn
LRvLR: 1v2 different sol - Camunda changes.
Seal claim form changes in camunda task 
https://tools.hmcts.net/jira/browse/CIV-2649
LRvLR: 1v2 different sol - Camunda changes.
```
[ ] Yes
[ ] No
```
=> feat/CIV-2649,  seal claim form changes in camunda bpmn diagram

bin/utils/process-definition.sh, config/owasp/suppressions.xml, src/main/resources/camunda/defendant_response_spec.bpmn
=> L rv lr master

config/owasp/suppressions.xml, src/main/resources/camunda/inform_agreed_extension_date_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InformAgreedExtensionDateSpecTest.java
This PR contains changes on Inform Agree Extension Date For Spec RPA
```
[ ] Yes
[ ] No
```
=> Inform Agree Extension Date For Spec RPA

src/main/resources/camunda/defendant_response_spec.bpmn
https://tools.hmcts.net/jira/browse/CIV-3313
RPA was notified only when both responses were available
```
[ ] Yes
[X] No
```
=> feat/1v2 RPA should be notified whenever a defendant responds

src/main/resources/camunda/generate_DJ_SDO_form.bpmn
=> CIV-1325 notifications

charts/civil-camunda/Chart.yaml
=> bump the ccd chart to 8.0.17

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-2991
https://tools.hmcts.net/jira/browse/CIV-2693
GA access profiles
```
[ ] Yes
[X] No
```
=> CIV-2693-2991 staff access profiles for GA

Jenkinsfile_CNP, bin/variables/load-staging-environment-variables.sh, charts/civil-camunda/values.aat.template.yaml, config/owasp/suppressions.xml
Fixing master to talk to https urls
```
[ ] Yes
[ ] No
```
=> Fixing master to talk to https urls

charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml
Upgrading charts version
```
[ ] Yes
[ x] No
```
=> Upgrading charts version

Jenkinsfile_CNP, build.gradle, charts/civil-camunda/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-2126
```
[ ] Yes
[ ] No
```
=> Add dj test

bin/add-roles.sh
New event HEARING_SCHEDULED
https://tools.hmcts.net/jira/browse/CIV-3315
```
[ ] Yes
[x ] No
```
=> added hearing-schedule-access

src/main/resources/camunda/defendant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantContactDetailsChangeCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-4571
This PR contains new camunda for the defendant respond the claim and there is contact details change in CUI part
```
[ ] Yes
[ ] No
```
=> CIV-4571: Contact details change LR email notification

.github/stale.yml
**No Jira link**
**Description**
The probot bots stopped working quite while back to swapping to new bot config
****Does this PR introduce a breaking change?** (check one with "x")**
```
[ ] Yes
[ x] No
```
=> adding new bot config for closing stale PR

src/main/resources/camunda/defendant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantContactDetailsChangeCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-4599
This PR contains the changes on the camunda diagram for claimant LR email notifications
```
[ ] Yes
[ ] No
```
=> CIV-4599: Defendant Response - Claimant LR email notifications

build.gradle
N/A
fix CVE-2022-38752
```
[ ] Yes
[X] No
```
=> FIX: CVE-2022-38752

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CIV-5049
Exclude HNL files on preview as to not impact SDO/DJ with the uplifted changes
```
[ ] Yes
[x] No
```
=> fix/exclude HNL files on preview

charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.aat.template.yaml
https://tools.hmcts.net/jira/browse/CIV-5215
- Bumping latest camunda version to avoid errors in db
- enabling imagePullPolicy for camunda in aat/staging pod
- force schema recreation with RELEASE_REVISION on dependant apps
```
[ ] Yes
[x] No
```
=> CIV-5270: Enhance Pipeline (Staging)

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-5223
new access-profile for PBAv3
```
[ ] Yes
[ x] No
```
=> access profile "payment-access" added

charts/civil-camunda/values.preview.template.yaml
CIV-5447
Fix LD key on preview
```
[ ] Yes
[x] No
```
=> LaunchDarkly key fix

build.gradle, charts/civil-camunda/values.preview.template.yaml, src/main/resources/camunda/generate_spec_DJ_form.bpmn
=> CIV-3322 Notification to caseworker

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/main/resources/camunda/create_service_request.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateServiceRequestTest.java
https://tools.hmcts.net/jira/browse/CIV-5245
camunda pbav3 changes for spec
```
[ ] Yes
[x ] No
```
=> civil-5245-camunda-spec-changes

src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java
Reverts hmcts/civil-camunda-bpmn-definition#393
=> DO NOT MERGE: Revert release: postpone clam deadline scheduler to 3am"

src/main/resources/camunda/hearing_fee_check_scheduler.bpmn, src/main/resources/camunda/trial_ready_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/HearingFeeCheckSchedulerTest.java
N/A
Disable Case Progression cron jobs
```
[ ] Yes
[x] No
```
=> Disabling of CP cron jobs

src/main/resources/camunda/trial_ready_scheduler.bpmn
=> corrected trial ready schduler business process name

Jenkinsfile_CNP, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml
CIV-6106
Removed user-profile-importer
Changed user-profile API to use AAT instance.
Increase ccd-data-store cpu
Disable camunda cron 
```
[ ] Yes
[ x ] No
```
=> CIV-6106 - Remove Dependencies on User Profile

Jenkinsfile_CNP, src/main/resources/camunda/create_claim.bpmn, src/main/resources/camunda/notify_claim.bpmn, src/main/resources/camunda/notify_claim_details.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDetailsTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimTest.java
* CIV-2356: Updated camunda flow
* CIV-2356: Updated variable name
* CIV-2356: Added unit test
* CIV-2356: Update create Claim bpm
* CIV-2356: Updated pipeline error
* CIV-2356: Updated caption of flows
* CIV-2356: Added test Cos service disabled
* Updated method name
```
[ ] Yes
[ ] No
```
=> cosintegration

Jenkinsfile_CNP, config/owasp/suppressions.xml
=> switch on cos

src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn, src/main/resources/camunda/polling_event_emitter_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java
Moving scheduler to trigger out of release hours (05:00) from 03:00
This will then be reverted as a post release activity
```
[ ] Yes
[ ] No
```
=> Postpone claim deadline scheduler to 5AM

src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java
=> revert scheduler changes

src/main/resources/camunda/polling_event_emitter_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java
Stopping poller till 9th Jan as per discussion with Akriti
=> Stopping poller till 9th Jan

charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml, charts/civil-camunda/values.yaml
CIV-5967
Remove Bitnami Dependency for postgres
```
[ ] Yes
[ x ] No
```
=> CIV-5967 - Remove Bitnami Dependency

src/main/resources/camunda/hearing_process.bpmn
https://tools.hmcts.net/jira/browse/CIV-6616
Task labels updated to clarify that the notifications are sent to solicitors of the claimant and defendant
```
[ ] Yes
[x] No
```
=> Task names updated

src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java
=> postpone clam deadline scheduler to 3am

src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java
=> Revert Deadline scheduler 

config/owasp/suppressions.xml, src/main/resources/camunda/notify_claim_deadline_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyClaimDeadlineSchedulerTest.java
=> revert notify deadline

Jenkinsfile_CNP, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-5369
https://tools.hmcts.net/jira/browse/CIV-5457
https://tools.hmcts.net/jira/browse/CIV-5961
Update the exclude the CUI nonprod
```
[ ] Yes
[x] No
```
=> CIV-5369: Exclude CUI-nonprod

.github/CODEOWNERS, .github/workflows/main.yml, charts/civil-camunda/values.preview.template.yaml
CIV-5433
Add PR Title validation 
Code Owners
```
[ ] Yes
[ x ] No
```
=> CIV-5433 - Add PR Title validation and Code Owners

src/main/resources/camunda/ga_hearing_scheduled_access.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GaHearingScheduledTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
https://tools.hmcts.net/jira/browse/CIV-6013
Added a new event to notify Respondents /Defendants separately.
```
[ ] Yes
[x ] No
```
=> CIV-6013 Added new event to notify defendants

src/main/resources/camunda/judge_makes_decision_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseJudgeGASpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/JudgeMakesDecisionGeneralApplicationTest.java
https://tools.hmcts.net/jira/browse/CIV-6925
Split judge make decision solicitor notification to have separate notification task for applicant and respondent
```
[ ] Yes
[ ] No
```
=> CIV-6925 Refactor solicitor notification event

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-3401
-add case flags access profiles to add roles script
```
[ ] Yes
[ ] No
```
=> CIV-3401 Access profiles for case flags

src/main/resources/camunda/resend_notify_rpa_events_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ResendNotifyRPASchedulerTest.java
https://tools.hmcts.net/jira/browse/SNI-3295
=> CIV-000 SNI-3295 new scheduler for resend notify rpa events

config/owasp/suppressions.xml
N/A
Just a CVE suppression
```
[ ] Yes
[x] No
```
=> CIV-TASK Adding suppression

.git-config/hooks/commit-msg, .git-config/hooks/pre-commit, .github/workflows/main.yml, README.md
https://tools.hmcts.net/jira/browse/CIV-7227
Enforcing conventions on branch names and commit messages
```
[ ] Yes
[x] No
```
=> CIV-7227 Enforcing conventions on branch names and commit messages

config/owasp/suppressions.xml
N/A
Suppress vulnerability that at the moment doesn't have a fix.
```
[ ] Yes
[x] No
```
=> CIV-TASK Adding suppression for CVE-2023-20860

.github/workflows/stale.yml, Dockerfile, build.gradle
N/A
Update multiple dependencies
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/551
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/547
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/546
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/545
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/544
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/543
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/521
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/506
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/504
```
[ ] Yes
[x] No
```
=> Update multiple dependencies

src/main/resources/camunda/generate_trial_ready_document_applicant.bpmn, src/main/resources/camunda/generate_trial_ready_document_respondent1.bpmn, src/main/resources/camunda/generate_trial_ready_document_respondent2.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateTrialReadyDocumentApplicantTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateTrialReadyDocumentRespondent1Test.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateTrialReadyDocumentRespondent2Test.java
=> CIV-6580 Adapt notifications to document process

bin/utils/process-definition.sh
CIV-0000 downgrading def processor version
```
[ ] Yes
[ ] No
```
=> CIV-0000 downgrading def processor version

bin/import-bpmn-diagram.sh
https://tools.hmcts.net/jira/browse/CIV-6668
Add tenant id "civil"
```
[ ] Yes
[ ] No
```
=> CIV-6668 add tenant-id to import-bpmn-diagram.sh

src/main/resources/camunda/defendant_response_cui.bpmn
https://tools.hmcts.net/jira/browse/CIV-7528
updated the CUI defendant response flow when defendant response language in Bilingual.
```
[ ] Yes
[x] No
```
=> CIV-7528 - Welsh - Bilingual language preference - NOTIFICATIONS SUPRESSION Defendant Submit with Welsh Flag

bin/add-roles.sh, build.gradle, config/owasp/suppressions.xml
CIV-0000- add wa role profile
```
[ ] Yes
[ ] No
```
=> CIV-0000 add wa role profile

build.gradle
=> CIV-6915 restore test

README.md, charts/civil-camunda/values.preview.template.yaml
=> CIV-0000 Fix why pipeline failing

config/owasp/suppressions.xml, src/main/resources/camunda/claimant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-7137
This PR contains changes for the Part Admit CYA and Submit Part
```
[ ] Yes
[x] No
```
=> CIV-7137 Part Admit States Paid - CYA and Submit

build.gradle
CIV-0000 fixing CVE
```
[ ] Yes
[x ] No
```
=> CIV-0000 fixing CVE

src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseGAAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseJudgeGASpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimServiceRequestTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateServiceRequestTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GaHearingScheduledTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/JudgeMakesDecisionGeneralApplicationTest.java
- removed remaining rpa tests thats not needed anymore
```
[ ] Yes
[ ] No
```
=> CIV-0000 remove remaining rpa tests

src/main/resources/camunda/apply_noc_decision.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionTest.java
https://tools.hmcts.net/jira/browse/CIV-6787
Notify new claimant rep of  hearing fee service request, if claimant rep changes via NOC. and fee unpaid
New tasks added to appy_noc_decision
```
[ ] Yes
[ x] No
```
=> CIV-6787 update to apply_noc_decision.bpmn for new tasks

src/main/resources/camunda/initiate_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java
https://tools.hmcts.net/jira/browse/CIV-7575
```
[ ] Yes
[x] No
```
=> CIV-7575 Adjourn or Vacate Hearing Fee Scenarios

src/main/resources/camunda/claimant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-7789
updated Camunda flow for claim in Mediation states.
```
[ ] Yes
[x] No
```
=> CIV-7789 - RPA Mediation

src/main/resources/camunda/polling_event_emitter_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java
Stopping poller till 20th June till we figure out what is the reason of retriggering event
=> CIV-0000 Stopping poller till 20th June

src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java
CIV-0000 Stopping errOR for multiple attempts 16thJune
=> CIV-0000 Stopping errOR for multiple attempts 16thJune

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-8884
added 2 new roles.
```
[ ] Yes
[x] No
```
=> CIV-8884 - CUI: create and link access roles

src/main/resources/camunda/spec-automated-hearing-notice-scheduler.bpmn, src/main/resources/camunda/unspec-automated-hearing-notice-scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/SpecAutomatedHearingNoticeSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UnspecAutomatedHearingNoticeSchedulerTest.java
Changed hearing scheduler conditions from javascript to expressions.
```
[ ] Yes
[X] No
```
=> CIV-6330 Hearing notice scheduler update

src/main/resources/camunda/claimant_response_spec.bpmn
https://tools.hmcts.net/jira/browse/CIV-8420
Add the pay Part Admit pay immediately scenario to the existing Part Admit agree Caumunda Notification
```
[ ] Yes
[x] No
```
=> CIV-8420 part admit pay immediately notification

src/main/resources/camunda/claimant_response_spec.bpmn, src/main/resources/camunda/request_judgement_by_admission.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RequestJudgementByAdmissionTest.java
https://tools.hmcts.net/jira/browse/CIV-6380
https://tools.hmcts.net/jira/browse/CIV-8034
https://tools.hmcts.net/jira/browse/CIV-9199
Change for RPA and the submit function for Request Judgment By Admission
Claimant Response
Request Judgment By Admission
```
[ ] Yes
[x] No
```
=> CIV-6380 RPA for ITP Additional Build 

config/owasp/suppressions.xml, src/main/resources/camunda/respondent_response_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RespondentResponseGeneralApplicationTest.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
https://tools.hmcts.net/jira/browse/CIV-9414
getting 403 error when respondent try to respond via api test
status":403,"error":"Forbidden: Insufficient permissions: Hash token check failed for the document: 09024ee0-be3d-4060-8573-4101a342a4b9","exception":"uk.gov.hmcts.reform.ccd.documentam.exception.ForbiddenException","timestamp":"22-06-2023 11:44:46.179","path":"/cases/documents/attachToCase"
**Does this PR introduce a breaking change?** …
=> CIV-9414 Added respondent response bpmn process flow

src/main/resources/camunda/generate_hearing_notice.bpmn, src/main/resources/camunda/start_hearing_notice_business_process.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateHearingNoticeTest.java
Implemented new StartHearingNoticeBusinessProcess diagram
```
[ ] Yes
[X] No
```
=> CIV-9344 automated hearing notice process

src/main/resources/camunda/initiate_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java
https://tools.hmcts.net/jira/browse/CIV-9383
Generate Draft Document for zero fee urgent application during initiate general application flow
```
[ ] Yes
[ ] No
```
=> CIV-9383 Generate Draft document for zero fee

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CIV-9513
***Test branch**
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/659
```
[ ] Yes
[ ] No
```
=> CIV-9513 Remove cui exclusion

charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml, charts/civil-camunda/values.yaml
https://tools.hmcts.net/jira/browse/CIV-7995
- add variable to values.yaml
```
[ ] Yes
[ ] No
```
=> CIV-7995 Add hmc enabled variable

src/main/resources/camunda/defendant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-8957
```
[ ] Yes
[ ] No
```
=> CIV-8957 generate lip dq

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-7897
Update add-roles.sh
```
[ ] Yes
[x] No
```
=> CIV-7897 - Update add-roles.sh

src/main/resources/camunda/hearing_process.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/HearingProcessTest.java
https://tools.hmcts.net/jira/browse/CIV-9730
```
[ ] Yes
[x] No
```
=> CIV-9730 fixed Hearing initiation is failing for LR vs Lip claim

build.gradle, config/owasp/suppressions.xml
Cleanup CVE issues
```
[ ] Yes
[x] No
```
=> CIV-0000 Cleanup CVE issues

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-5339
added new profile
```
[ ] Yes
[x] No
```
=> CIV-5339 - Release 2 - LIP v LIP Update Access Profile JSON 

src/main/resources/camunda/create_service_request_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimServiceRequestTest.java
https://tools.hmcts.net/jira/browse/CIV-9253
Update to create_service_request_claim diagram to enable bulk claim payments immediately after service request generated
```
[ ] Yes
[ x] No
```
=> CIV-9253 update create service request claim for bulk claims

src/main/resources/camunda/create_lip_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimLipTest.java
https://tools.hmcts.net/jira/browse/CIV-8918
Lip case assignment
```
[ ] Yes
[x] No
```
=> CIV-8918 Claim Submission - Assign Claim

src/main/resources/camunda/claimant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-10048
add dq for claimant generation in mediation journey
```
[ ] Yes
[ ] No
```
=> CIV-1048 add claimant dq generation to mediation journey

.github/workflows/main.yml
updated the PR title length from 4 to 5 for longer CIV ticket numbers
```
[ ] Yes
[x] No
```
=> CIV-00000 Changing naming pattern for prs

src/main/resources/camunda/create_claim_spec_after_payment.bpmn
https://tools.hmcts.net/jira/browse/CIV-10126
Set Up LiP Claim Issue After Payment
```
[ ] Yes
[x] No
```
=> CIV-10126 Set Up Lip Claim Issue After Payment 

src/main/resources/camunda/create_claim_spec_after_payment.bpmn
Rename on the path because of confusion
```
[ ] Yes
[x] No
```
=> CIV-0000 Rename on the path because of confusion

src/main/resources/camunda/applicant_trial_ready_notify_others.bpmn, src/main/resources/camunda/respondent1_trial_ready_notify_others.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplicantTrialReadyNotifyOthersTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/Respondent1TrialReadyNotifyOthersTest.java
https://tools.hmcts.net/jira/browse/CIV-9407
Conditions in diagrams modified to work with LiP
```
[ ] Yes
[x] No
```
=> CIV-9407 Trial Arrangements: Email Notification to Citizen on Completion of Trial Arrangements by the Defendant LiP

Jenkinsfile_CNP
=> CIV-0000 Update Jenkinsfile_CNP

src/main/resources/camunda/respond_to_addln_info_general_application.bpmn, src/main/resources/camunda/respond_to_directions_general_application.bpmn, src/main/resources/camunda/respond_to_written_rep_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RespondToAddlnInfoGeneralApplicationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RespondToDirectionsGeneralApplicationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RespondToWrittenRepGeneralApplicationTest.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
https://tools.hmcts.net/jira/browse/CIV-9804
To Avoid 403 Forbidden error while uploading a document from general application, added a new bpmn flows for Respond to Judge Directions, Respond to Judge Additional Info, Respond to Judge Written Representations.
```
[ ] Yes
[x ] No
```
=> CIV-9804 Added new BPMN flows for Response to Judge Directions for uploading a document to Main case

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-8821
Added notification event when claimant submit his response.
```
[ ] Yes
[x] No
```
=> CIV-8821 - Claimant Intent: Generic notification to defendant

src/main/resources/camunda/enter_breathing_space_lip.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/EnterBreathingSpaceLipTest.java
https://tools.hmcts.net/jira/browse/CIV-6719
Notification Debt Respite Submit Function
```
[ ] Yes
[x] No
```
=> CIV-6719 Notification Debt Respite Submit Function

src/main/resources/camunda/create_lip_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimLipTest.java
https://tools.hmcts.net/jira/browse/CIV-8998
Added notification event for create LiP claim flow
```
[ ] Yes
[x] No
```
=> CIV-8998 -Added notification event for create LiP claim flow

build.gradle, config/owasp/suppressions.xml
=> CIV-0000 fix cve issue

config/owasp/suppressions.xml, src/main/resources/camunda/claimant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-10686
```
[ ] Yes
[ ] No
```
=> CIV-10686 LR Claimant Intention Notification

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-10823
```
[ ] Yes
[x] No
```
=> CIV-10823 new role added for pcq

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/CIV-10391
respondent1 response deadline activity added
```
[ ] Yes
[ ] No
```
=> CIV-10391 Respondent1 response deadline date update

charts/civil-camunda/Chart.yaml, src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-8941
Added IN_MEDAITION flow
```
[ ] Yes
[x] No
```
=> CIV-8941 - added In Mediation flow in claimant response journey.

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-10519
```
[ ] Yes
[ ] No
```
=> CIV-10519 add claimant dq generation to claimant response

Jenkinsfile_CNP, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml
add passwords secretes
```
[ ] Yes
[X] No
```
=> CIV-10624 add passwords secrets

src/main/resources/camunda/bundle_creation_scheduler.bpmn, src/main/resources/camunda/decision_outcome_scheduler.bpmn, src/main/resources/camunda/evidence_upload_scheduler.bpmn, src/main/resources/camunda/hearing_fee_check_scheduler.bpmn, src/main/resources/camunda/trial_ready_check_scheduler.bpmn, src/main/resources/camunda/trial_ready_notification_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BundleCreationSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DecisionOutcomeSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/EvidenceUploadSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/HearingFeeCheckSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TrialReadyCheckSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TrialReadyNotificationSchedulerTest.java
https://tools.hmcts.net/jira/browse/CIV-5023
Removed schedulers for case progressoin release
```
[ ] Yes
[x] No
```
=> CIV-5023 - updated schedulers to remove 2024 limit

src/main/resources/camunda/claimant_response_cui.bpmn
https://tools.hmcts.net/jira/browse/CIV-8938
```
[ ] Yes
[x] No
```
=> CIV-8938 claimant intent submit function change state to judicial referral

src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/request_judgement_by_admission.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RequestJudgementByAdmissionTest.java
https://tools.hmcts.net/jira/browse/CIV-8938
https://tools.hmcts.net/jira/browse/CIV-9025
```
[ ] Yes
[ ] No
```
=> CIV-0000 Post case progression tasks to be merged

src/main/resources/camunda/retrigger_cases_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RetriggerCasesSchedulerTest.java
https://tools.hmcts.net/jira/browse/CIV-11363
Add Scheduler to retrigger cases
```
[ ] Yes
[X] No
```
=> CIV-11363 Add scheduler to retrigger cases

src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/create_lip_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimLipTest.java
---------
https://tools.hmcts.net/jira/browse/CIV-11571
https://tools.hmcts.net/jira/browse/CIV-11315
https://tools.hmcts.net/jira/browse/CIV-11236
https://tools.hmcts.net/jira/browse/CIV-10612
https://tools.hmcts.net/jira/browse/CIV-10440
https://tools.hmcts.net/jira/browse/CIV-9662
https://tools.hmcts.net/jira/browse/CIV-8241
https://tools.hmcts.net/jira/browse/CIV-8147
https://tools.hmcts.net/jira/browse/CIV-11230
https://tools.hmcts.net/jira/browse/CIV-11695
https://tools.hmcts.net/jira/browse/CIV-8905
https://tools.hmcts.net/jira/browse/CIV-8454
```
[ ] Yes
[ ] No
```
=> CIV-0000 Bulk tasks to Master

config/owasp/suppressions.xml
=> CIV-0000 Update suppressions.xml

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/CIV-8791
```
[ ] Yes
[x] No
```
=> CIV-8791 Claimant notification

src/main/resources/camunda/claimant_response_cui.bpmn
https://tools.hmcts.net/jira/browse/CIV-11473
```
[ ] Yes
[ ] No
```
=> CIV-11473 Populate Case Management Location on completion of all defendant response journeys

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
=> CIV-0000 Removing notify applicant step

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
=> CIV-11950 Remove RPA task for CUI journey

.github/renovate.json
=> CIV-0000 changes to renovate

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-11603
Changes for submission for fast track claimant intent
Changing on the condition for checking
```
[ ] Yes
[x] No
```
=> CIV-11603 Fast Track Claimant Intent

charts/civil-camunda/values.preview.template.yaml
=> CIV-0000 using old gateway image as latest is broken

src/main/resources/camunda/apply_help_with_hearing_fee.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyHelpWithHearingFeeTest.java
https://tools.hmcts.net/jira/browse/CIV-11209
```
[ ] Yes
[ x ] No
```
=> CIV-11209 Apply help with hearing fee

config/owasp/suppressions.xml, src/main/resources/camunda/apply_noc_decision_lip.bpmn, src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/defendant_sign_settlement_agreement.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionLipTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantSignSettlementAgreementTest.java
https://tools.hmcts.net/jira/browse/CIV-11523
https://tools.hmcts.net/jira/browse/CIV-8903
https://tools.hmcts.net/jira/browse/CIV-11542
https://tools.hmcts.net/jira/browse/CIV-11260
https://tools.hmcts.net/jira/browse/CIV-10547
https://tools.hmcts.net/jira/browse/CIV-11986
https://tools.hmcts.net/jira/browse/CIV-11938
https://tools.hmcts.net/jira/browse/CIV-11965
https://tools.hmcts.net/jira/browse/CIV-11213
https://tools.hmcts.net/jira/browse/CIV-11161
https://tools.hmcts.net/jira/browse/CIV-11603
https://tools.hmcts.net/jira/browse/CIV-11969
https://tools.hmcts.net/jira/browse/CIV-11699
https://tools.hmcts.net/jira/browse/CIV-11091 …
=> CIV-0000 Sprint pi32 s5 t4 to master 

src/main/resources/camunda/apply_noc_decision_lip.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionLipTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-11694
https://tools.hmcts.net/jira/browse/CIV-11697
Notification for Notice of Change
```
[ ] Yes
[x] No
```
=> CIV-11697 Notify Defendant LiP claimant is now represented 

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
=> CIV-12291 Enable RPA for  LR vs Lip claims

src/main/resources/camunda/notify_lip_generic_template.bpmn
https://tools.hmcts.net/jira/browse/CIV-7829
Add new camunda process to notify LIP 1
```
[ ] Yes
[x] No
```
=> CIV-7829 adding generic lip generic template process

src/main/resources/camunda/bundle_creation_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BundleCreationSchedulerTest.java
Stopping bundling scheduler for stitching flexible db release
=> CIV-0000 Stopping bundling scheduler for stitching flexible db release

src/main/resources/camunda/notify_lip_generic_template.bpmn
PR to merge Temp branch to master
=> CIV-00000 Team2b temp release

src/main/resources/camunda/bundle_creation_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BundleCreationSchedulerTest.java
Reverts hmcts/civil-camunda-bpmn-definition#849
=> CIV-0000 Stopping bundling scheduler for stitching flexible db release Revert 

src/main/resources/camunda/notify_decision_on_reconsideration_request.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyDecisionOnReconsiderationRequestTest.java
* Create notify_claim_reconsideration_upheld.bpmn
CIV-10909  New process file to trigger the emial send
* Update notify_claim_reconsideration_upheld.bpmn
CIV-10909 Change the principal event name for the process
* CIV-10909 Rename the bpm file
* CIV-10909 Refactoring the business process to notify the claim changes
* CIV-10909 Refactoring the business process to notify the claim changes
* CIV-11244 adding an event to trigger the document generation
* CIV-11244 adding an event to trigger the document generation
* CIV-11244 Modify the test for the new event
* CIV-11244 Modified test comments
---------
**Does this PR introduce a breaking change?** (check one with …
=> CIV-0000 sprint branch

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/CIV-12265
Email Notification to Claimant LiP in Bilingual Claim Issue
```
[ ] Yes
[x ] No
```
=> CIV-12265 Email Notification to Claimant LiP in Bilingual Claim Issue

src/main/resources/camunda/upload_translated_document_claim_issue_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimIssueDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-12285
Claim Issue submit notifications - translated documents uploaded
```
[ ] Yes
[x ] No
```
=> CIV-12285 Claim Issue submit notifications - translated documents uploaded

config/owasp/suppressions.xml, src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/upload_translated_claimant_intention_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantIntentionDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-12045
Updated Camunda Flow for claimant Intention 
```
[ ] Yes
[x] No
```
=> CIV-12045 - Work allocation to CTSC Case worker : Case work enter the Judgement manually

config/owasp/suppressions.xml, src/main/resources/camunda/upload_translated_claimant_intention_document_notify.bpmn, src/main/resources/camunda/upload_translated_document_claim_issue_notify.bpmn, src/main/resources/camunda/upload_translated_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyTranslatedDocumentUploadedTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimIssueDocumentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantIntentionDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-11807
Updated Event name as existing event name was too long.
```
[ ] Yes
[x] No
```
=> CIV-11807 - SDO DMN for Part Admit Journeys/ Defence journey - Release 2

src/main/resources/camunda/create_lip_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimLipTest.java
=> CIV-12654 Claim fee required dashboard notification

src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/upload_translated_claimant_intention_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantIntentionDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-12741
Claimant_response_cui.bpmn:
upload_translated_claimant_intention_document_notify.bpmn:
```
[ ] Yes
[ ] No
```
=> CIV-12741 Claim Issue in Welsh - Send RPA

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/CIV-12691
Dashboard Notification - When claim gets issued 
```
[ ] Yes
[x] No
```
=> CIV-12691 Create Claimant dashboard notifications for issue claim

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/CIV-12693
Dashboard Notification - When claim gets issued (Defendant)
```
[ ] Yes
[x] No
```
=> CIV-12693 Create defendant dashboard notification for Issue claim

charts/civil-camunda/values.preview.template.yaml
=> CIV-10543 pointing_to_v15

src/main/resources/camunda/create_lip_claim.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimLipTest.java
https://tools.hmcts.net/jira/browse/CIV-12757
```
[ ] Yes
[ x ] No
```
=> CIV-12757 Dashboard Notification HWF

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/CIV-13015
Create defendant notifications when LRVLIP claim
```
[ ] Yes
[ ] No
```
=> CIV-13015 Create defendant notifications when LRVLIP claim

src/main/resources/camunda/generate_spec_DJ_form.bpmn, src/main/resources/camunda/request_judgement_by_admission.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RequestJudgementByAdmissionTest.java
https://tools.hmcts.net/jira/browse/CIV-12742
```
[ ] Yes
[x] No
```
=> CIV-12742 - added dashboard notification handler.

src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/claimant_response_spec.bpmn, src/main/resources/camunda/upload_translated_claimant_intention_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantIntentionDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-12758
https://tools.hmcts.net/jira/browse/CIV-12758
```
[ ] Yes
[x ] No
```
=> CIV-12758 Dashboard notification - Claim settled (Defendant)

src/main/resources/camunda/full_admit_pay_immediately_no_payment_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/FullAdminPayImmediatelyNoPaymentSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/FullAdmitPayImmediatelyNoPaymentSchedulerTest.java
[CIV-12962](https://tools.hmcts.net/jira/browse/CIV-12962)
Add scheduler for full admit pay immediately no payment
```
[ ] Yes
[ ] No
```
=> CIV-12962 Add scheduler for full admit pay immediately no payment

src/main/resources/camunda/settlement_no_defendant_response_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/SettlementNoResponseFromDefendantSchedulerTest.java
[CIV-12960](https://tools.hmcts.net/jira/browse/CIV-12960)
CIV 12960 Add scheduler for settlement no defendant response
```
[ ] Yes
[ ] No
```
=> CIV-12960 Add scheduler for settlement no defendant response

src/main/resources/camunda/notify_lip_generic_template.bpmn
https://tools.hmcts.net/jira/browse/CIV-12614
=> CIV-12614 - payment ccd update

src/main/resources/camunda/upload_translated_document_claim_issue_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimIssueDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-13065
Claimant pays claim fee over the phone
```
[ ] Yes
[x] No
```
=> CIV-13065 Claimant pays claim fee over the phone

src/main/resources/camunda/defendant_response_cui.bpmn, src/main/resources/camunda/upload_translated_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyTranslatedDocumentUploadedTest.java
https://github.com/hmcts/civil-ccd-definition/pull/4162
Dashboard changes for Defendant Response
upload_translated_document_notify.bpmn
defendant_response_cui.bpmn
```
[ ] Yes
[x] No
```
=> CIV-13119 - Dashboard Defendant Response Part Admit pay immediately

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-13298
```
[ ] Yes
[ ] No
```
=> CIV-13298 Camunda error during ClaimantIntention Full defence DisputetAllnges

src/main/resources/camunda/defendant_sign_settlement_agreement.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantSignSettlementAgreementTest.java
https://tools.hmcts.net/jira/browse/CIV-12895
```
[ ] Yes
[x] No
```
=> CIV-12895 defendant sign settlement agreement

src/main/resources/camunda/record_judgment_notification.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RecordJudgmentDeterminationMeansNotificationTest.java
https://tools.hmcts.net/jira/browse/CIV-13134
```
[ ] Yes
[ ] No
```
=> CIV-13134 Record judgment notification

src/main/resources/camunda/extend_response_deadline.bpmn, src/main/resources/camunda/inform_agreed_extension_date_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ExtendResponseDeadlineTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InformAgreedExtensionDateSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-13072
```
[ ] Yes
[X] No
```
=> CIV-13072 dr more time requested

src/main/resources/camunda/inform_agreed_extension_date_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InformAgreedExtensionDateSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-13071
Claimant dashboard defendant requests more time
```
[ ] Yes
[x] No
```
=> CIV-13071 Claimant dashboard defendant requests more time

bin/utils/process-definition.sh
=> CIV-0000 Remove ip address that was unintentionally committed

charts/civil-camunda/values.preview.template.yaml, src/main/resources/camunda/mediation_successful.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/MediationSuccessfulTest.java
https://tools.hmcts.net/jira/browse/CIV-13149
After fixing merge conflicts, NEW camunda diagram
```
[ ] Yes
[x] No
```
=> CIV-13149 Add dashboard notifications for mediation successful

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-13070
Judgment Requested (claimant has accepted the repayment plan) (By Admission -Defendant)
```
[ ] Yes
[x] No
```
=> CIV-13070 claimant has accepted the repayment plan ccj

src/main/resources/camunda/notify_judgement_varied_determination_of_means.bpmn, src/main/resources/camunda/notify_judgment_varied_determination_of_means.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyJudgmentVariedDeterminationOfMeansTest.java
[CIV-13171- Email notifications: Claimant/Defendant LR - Judgment varied following Determination of Means](https://tools.hmcts.net/jira/browse/CIV-13171)
These notifications are generated following the editing of a Judgment by a caseworker after a determination of means
**Test of Email Notification:**
_Applicant:_
https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/notification/b8e0cc53-8c8d-4be8-ac70-20cace8ce25a?from_statuses=sending,delivered,failed
_Defendant:_
https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/notification/cea339f3-03c2-4897-9433-b1f9df33e010
_Applicant:_
https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/notification/e8ac41e0-22af-4df0-986c-3e63d4b1a0b3?from_sta …
=> CIV-13171 Email notifications Judgment varied following Determination of Means

src/main/resources/camunda/mediation_unsuccessful.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/MediationUnsuccessfulTest.java
https://tools.hmcts.net/jira/browse/CIV-13283
```
[ ] Yes
[ ] No
```
=> CIV-13283 Dashboard service flag

src/main/resources/camunda/mediation_unsuccessful.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/MediationUnsuccessfulTest.java
=> CIV-0000 - modified mediation unsuccessful bpmn and test.

src/main/resources/camunda/bundle_creation_notification.bpmn, src/main/resources/camunda/hearing_process.bpmn, src/main/resources/camunda/trial_ready_notification.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BundleCreationNotificationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/HearingProcessTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TrialReadyNotificationTest.java
hearing_process.bppmn
bundle_creation_notification.bpmn
trail_ready_notification.bpmn
```
[ ] Yes
[ ] No
```
=> CIV-0000 Dashboard flag

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSCCI-60
Reduce CVEs
```
[ ] Yes
[ ] No
```
=> DTSCCI-060 Reduce CVEs

src/main/resources/camunda/polling_event_emitter_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-17
```
[ ] Yes
[ ] No
```
=> DTSCCI-017 changing the poller back to 5min intervals

src/main/resources/camunda/create_sdo.bpmn, src/main/resources/camunda/generate_order_notification.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateSDOTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateOrderNotificationTest.java
=> CIV-0000 Dashboard changes

src/main/resources/camunda/polling_event_emitter_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/PollingEventEmitterSchedulerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-17
```
[ ] Yes
[ ] No
```
=> DTSCCI-017 enable polling event

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSCCI-60
Reduce CVEs number
```
[ ] Yes
[ ] No
```
=> DTSCCI-060 Reduce CVEs number

src/main/resources/camunda/generate_non_divergent_spec_DJ_form.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateNonDivergentSpecDJFormTest.java
https://tools.hmcts.net/jira/browse/CIV-12877
Added step in flow to call Handler for DJ Non-Divergent Spec Post PIN in Letter for Defendant1 LiP
```
[ ] Yes
[ ] No
```
=> CIV-12877 Changes to DJ Non-Divergent Spec Post PIN in Letter flow

src/main/resources/camunda/notify_decision_on_reconsideration_request.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyDecisionOnReconsiderationRequestTest.java
https://tools.hmcts.net/jira/browse/CIV-13728
```
[ ] Yes
[ ] No
```
=> CIV-13728 update decision reconsideration camunda

src/main/resources/camunda/defendant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-13311
Set up claimant dashboard for defendant submit in welsh
```
[ ] Yes
[x] No
```
=> CIV-13498 Defendant submits in Welsh Dashboard for Claimant 

src/main/resources/camunda/case_proceeds_in_caseman.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CaseProceedsInCasemanTest.java
https://tools.hmcts.net/jira/browse/CIV-13495
```
[ ] Yes
[ ] No
```
=> CIV-13495 Dashboard notification - Case proceeds offline

src/main/resources/camunda/generate_non_divergent_spec_DJ_form.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateNonDivergentSpecDJFormTest.java
https://tools.hmcts.net/jira/browse/CIV-12877
```
[ ] Yes
[ ] No
```
=> CIV-12877 Changes to DJ Non-Divergent Spec Post PIN in Letter flow 

src/main/resources/camunda/judgement_by_admission_non_divergent_spec.bpmn, src/main/resources/camunda/request_non_divergent_judgement_by_admission.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RequestNonDivergentJudgementByAdmissionTest.java
[CIV-13272](https://tools.hmcts.net/jira/browse/CIV-13272)
Stop RPA for Judgment by Admission against Defendant LR/LIP
```
[ ] Yes
[x] No
```
=> CIV-13272 Stop RPA for Judgment by Admission against Defendant LR/LIP

src/main/resources/camunda/generate_non_divergent_spec_DJ_form.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateNonDivergentSpecDJFormTest.java
[CIV-12893](https://tools.hmcts.net/jira/browse/CIV-12893)
Defendant LiP dashboard notifications: Default judgment issued
```
[ ] Yes
[x] No
```
=> CIV-12893 Defendant LiP dashboard notifications: Default judgment issued

src/main/resources/camunda/judgement_by_admission_non_divergent_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RequestNonDivergentJudgementByAdmissionTest.java
[CIV-13792](https://tools.hmcts.net/jira/browse/CIV-13792)
Defendant LiP dashboard notifications: judgment by admission issued
```
[ ] Yes
[x] No
```
=> CIV-13792 Defendant LiP dashboard notifications: judgment by admission issued

src/main/resources/camunda/notify_decision_on_reconsideration_request.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyDecisionOnReconsiderationRequestTest.java
https://tools.hmcts.net/jira/browse/CIV-13717
Decision on reconsideration dashboard changes
```
[ ] Yes
[x] No
```
=> CIV-13717 - decision on reconsideration dashboard

bin/create-github-release.sh, bin/pull-latest-release-asset.sh, bin/utils/idam-lease-user-token.sh
=> DTSCCI-000 jq patch

src/main/resources/camunda/upload_translated_document_order_notice.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedDocumentOrderNoticeTest.java
https://tools.hmcts.net/jira/browse/CIV-14124
```
[ ] Yes
[x] No
```
=> CIV-14124 - translated order notification

src/main/resources/camunda/validate_discontinue_claim_claimant.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ValidateDiscontinueClaimClaimantTest.java
=> CIV-14295 Claimant LR Email notification: please resubmit discontinuance

src/main/resources/camunda/upload_translated_document_order_notice.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedDocumentOrderNoticeTest.java
https://tools.hmcts.net/jira/browse/CIV-14193
```
[ ] Yes
[ x ] No
```
=> CIV-14193 Bulk print translated order

src/main/resources/camunda/validate_discontinue_claim_claimant.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ValidateDiscontinueClaimClaimantTest.java
=> CIV-14552 VALIDATE_DISCONTINUE_CLAIM_CLAIMANT event: notifications

src/main/resources/camunda/amend_restitch_bundle.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/AmendRestitchBundleTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-14593
=> CIV-14593 New BPMN To Send Notification After Bundle Is Re-stitched

src/main/resources/camunda/end_ga_business_process.bpmn, src/main/resources/camunda/end_ga_hwf_notify_process.bpmn, src/main/resources/camunda/notify_ga_applicant_hwf_outcome.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseGASpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GaHwfNotifyTest.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
https://tools.hmcts.net/jira/browse/CIV-12762
CIV-12772
CIV-12766
CIV-12763
Claimant Notification for All caseworker HWF events
```
[ ] Yes
[x ] No
```
=> CIV-12772 Application Fee - Claimant Notification - For all caseworker events

src/main/resources/camunda/amend_restitch_bundle.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/AmendRestitchBundleTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-14595
=> CIV-14595 adding tasks for claimant and defendant dashboard notification

src/main/resources/camunda/claimant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-14783
Added changes in Claimant_response_spec.bpmn'  when the claim is Lr v Lip  and claimant intention is Full Defence + Full Dispute 
then claim suppose to move to Case_Stayed state instead 'Procced_In_Heritage' post CUI R2 release.
```
[ ] Yes
[x] No
```
=> CIV-14783 - Full defence, full dispute: Claimant does not proceed with the claim

src/main/resources/camunda/end_doc_upload_general_application_business_process.bpmn, src/main/resources/camunda/upload_additional_doc_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseGAAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadAdditionalDocumentsGenAppTest.java
SNI-5921
disallow upload additional event to create wa task
```
[ ] Yes
[ ] No
```
=> DTSCCI-000 SNI-5921 disallow upload additional event to create wa task

src/main/resources/camunda/create_sdo.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateSDOTest.java
https://tools.hmcts.net/jira/browse/CIV-14881
I added changes to send the SDO order to the LiP Claimant.
```
[ ] Yes
[x ] No
```
=> CIV-14881 - Send SDO order to LiP Claimant.

src/main/resources/camunda/end_general_application_business_process.bpmn, src/main/resources/camunda/initiate_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java
https://tools.hmcts.net/jira/browse/CIV-14813
https://tools.hmcts.net/jira/browse/CIV-14813
```
[ ] Yes
[x ] No
```
=> CIV-14813 Updated task list for claimant and defendant

src/main/resources/camunda/stay_case.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/StayCaseTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-14748 & https://tools.hmcts.net/jira/browse/CIV-14749
=> CIV-14748 Generate Email Notification When Case Is Stayed

src/main/resources/camunda/dismiss_case.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DismissCaseTest.java
https://tools.hmcts.net/jira/browse/CIV-14827
https://tools.hmcts.net/jira/browse/CIV-14828
Email notifications when a case is dismissed
```
[ ] Yes
[X] No
```
=> CIV-14827 and 28 notification when dismiss case

src/main/resources/camunda/amend_restitch_bundle.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/AmendRestitchBundleTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-14879
=> CIV-14748 Add 5 Minutes Delay Before Notifications

src/main/resources/camunda/create_sdo.bpmn, src/main/resources/camunda/end_general_application_business_process.bpmn, src/main/resources/camunda/initiate_general_application.bpmn, src/main/resources/camunda/record_judgment_notification.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateSDOTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RecordJudgmentDeterminationMeansNotificationTest.java
https://tools.hmcts.net/jira/browse/CIV-14869
- Added new process in record judgment
```
[ ] Yes
[ ] No
```
=> CIV-14869 CJES Service : RECORD_JUDGMENT

src/main/resources/camunda/notify_judgment_varied_determination_of_means.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyJudgmentVariedDeterminationOfMeansTest.java
https://tools.hmcts.net/jira/browse/CIV-14809
notify_judgment_varied_determination_of_means.bpmn 
```
[ ] Yes
[ ] No
```
=> CIV-14809 Add Camunda task EDIT_JUDGMENT

src/main/resources/camunda/generate_non_divergent_spec_DJ_form.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateNonDivergentSpecDJFormTest.java
[CIV-14804 Changes to call to CJES for Default Judgment update](https://tools.hmcts.net/jira/browse/CIV-14804)
As HMCTS
I want to add Camunda task for Default judgment
So that RTL is updated via call to CJES
```
[ ] Yes
[X] No
```
=> CIV-14804 Changes to call to CJES for Default Judgment update

src/main/resources/camunda/generate_non_divergent_spec_DJ_form.bpmn, src/main/resources/camunda/judgment_by_admission_non_divergent_spec.bpmn, src/main/resources/camunda/notify_judgment_varied_determination_of_means.bpmn, src/main/resources/camunda/record_judgment_notification.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateNonDivergentSpecDJFormTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyJudgmentVariedDeterminationOfMeansTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RecordJudgmentDeterminationMeansNotificationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RequestNonDivergentJudgmentByAdmissionTest.java
sprint branch for CJES services: CIV-14869, 14809, 14804, 14807
```
[ ] Yes
[ ] No
```
=> CIV-0000 sprint branch for CJES services: CIV-14869, 14809, 14804, 14807

src/main/resources/camunda/initiate_general_application_after_payment.bpmn, src/main/resources/camunda/judge_makes_decision_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/JudgeMakesDecisionGeneralApplicationTest.java
=> CIV-0000 Bulk cui sprint branch 

src/main/resources/camunda/ga_hwf_add_update.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GaHwfAddUpdateTest.java
https://tools.hmcts.net/jira/browse/CIV-15218
fix case status after addl payment
```
[ ] Yes
[x] No
```
=> CIV-15218 add new process to update case after hwf additional fee

src/main/resources/camunda/notify_ga_applicant_hwf_outcome.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GaHwfNotifyTest.java
https://tools.hmcts.net/jira/browse/CIV-14430
Dashboard Notification - GA for LiPs
```
[ ] Yes
[x] No
```
=> CIV-14430 Dashboard notification for GA Lip Hwf

src/main/resources/camunda/general_application_judge_makes_order_after_hearing.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GeneralApplicationJudgeMakesOrderAfterHearingTest.java
https://tools.hmcts.net/jira/browse/CIV-14410
```
[ ] Yes
[ ] No
```
=> CIV-0000 Bulk sp4 to master

src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/upload_translated_claimant_intention_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantIntentionDocumentTest.java
CIV-15043 LipvLip Dashboard notification for JO issued 
---------
```
[ ] Yes
[ ] No
```
=> CIV-0000 Sprint branch JO - CIV-15043

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-15062
Add ctsc roles
```
[ ] Yes
[x] No
```
=> CIV-15062 - Add ctsc roles

src/main/resources/camunda/amend_restitch_bundle.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/AmendRestitchBundleTest.java
https://tools.hmcts.net/jira/browse/CIV-15204
Amend restitch dashboard behind feature toggle for case progression
```
[ ] Yes
[x] No
```
=> CIV-15204 - put amend restitch behind feature toggle

Jenkinsfile_CNP, charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml, charts/civil-camunda/values.yaml
Added wiremock to camunda preview pipeline
```
[ ] Yes
[ ] No
```
=> CIV-0000 Added wiremock to camunda preview pipeline

src/main/resources/camunda/claimant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-15042
service: https://github.com/hmcts/civil-service/pull/5396
Do not take case offline when pay immediately is done on claimant response
```
[ ] Yes
[ ] No
```
=> CIV-15042 Do not take case offline when pay immediately is done on claimant response

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/main/resources/camunda/upload_translated_document_claim_issue_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimIssueDocumentTest.java
NA
Added a RPA continuous feed task when LiP v LIp claim is issued.
```
[ ] Yes
[ ] No
```
=> CIV-0000 - RPA task for Lip v lip claims

src/main/resources/camunda/generate_order_notification.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateOrderNotificationTest.java
https://tools.hmcts.net/jira/browse/CIV-15268
```
[ ] Yes
[ x ] No
```
=> CIV-15268 hearing documents on further hearing

src/main/resources/camunda/stay_lifted.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/StayLiftedTest.java
https://tools.hmcts.net/jira/browse/CIV-15229
```
[ ] Yes
[ x ] No
```
=> CIV-15229 Dashboard notification stay lifted

src/main/resources/camunda/end_general_application_business_process.bpmn, src/main/resources/camunda/end_judges_makes_decision_business_process.bpmn, src/main/resources/camunda/initiate_general_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GeneralApplicationJudgeMakesOrderAfterHearingTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/JudgeMakesDecisionGeneralApplicationTest.java
https://tools.hmcts.net/jira/browse/CIV-14568
Update CUI task list
```
[ ] Yes
[x] No
```
=> CIV-14568 Update CUI task list

src/main/resources/camunda/defendant_response_deadline_check_scheduler.bpmn, src/main/resources/camunda/full_admit_pay_immediately_no_payment_scheduler.bpmn, src/main/resources/camunda/settlement_no_defendant_response_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseDeadlineCheckSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/FullAdmitPayImmediatelyNoPaymentSchedulerTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/SettlementNoResponseFromDefendantSchedulerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-1171
```
[ ] Yes
[ ] No
```
=> DTSCCI-1171 - Remove 2026 from cron cycle

bin/utils/process-definition.sh
=> DTSCCI-813 ccd defs dynamic case type

src/main/resources/camunda/manage_stay_wa_task_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ManageStayWATaskSchedulerTest.java
https://tools.hmcts.net/jira/browse/CIV-15226
- Added new manage stay WA task scheduler process.
```
[ ] Yes
[X] No
```
=> CIV-15226 Manage Stay WA Task Scheduler 

src/main/resources/camunda/general_application_response_deadline_processor.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GAResponseDeadlineProcessorTest.java
DTSCCI-947
fix cron expression
```
[ ] Yes
[ ] No
```
=> DTSCCI-947 fix cron expression

bin/utils/process-definition.sh, src/main/resources/camunda/judgment_by_admission_non_divergent_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RequestNonDivergentJudgmentByAdmissionTest.java
https://tools.hmcts.net/jira/browse/CIV-15748
```
[ ] Yes
[ ] No
```
=> CIV-15748 RPA changes - JBA live feed

src/main/resources/camunda/apply_noc_decision_defendant_lip.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionDefendantLipTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java
https://tools.hmcts.net/jira/browse/CIV-15958
Go to end process - ${(empty flowFlags.LIP_CASE || !flowFlags.LIP_CASE) || (!empty flowFlags.DEFENDANT_NOC_ONLINE && flowFlags.DEFENDANT_NOC_ONLINE)}
Go offline - ${(!empty flowFlags.LIP_CASE && flowFlags.LIP_CASE) && (empty flowFlags.DEFENDANT_NOC_ONLINE || !flowFlags.DEFENDANT_NOC_ONLINE)}
```
[ ] Yes
[x] No
```
=> CIV-15958 DEFENDANT_NOC_ONLINE

src/main/resources/camunda/take_case_offline.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TakeCaseOfflineTest.java
https://tools.hmcts.net/jira/browse/CIV-16012
Added a 'isDahsboardEnable' gateway in take_case_offline flow. 
```
[ ] Yes
[x] No
```
=> CIV-16012 - Gateway condition is not evaluated properly for GA for LiP's BPMN's

src/main/resources/camunda/apply_noc_decision_defendant_lip.bpmn, src/main/resources/camunda/apply_noc_decision_lip.bpmn
=> DTSCCI-000 Rename process

charts/civil-camunda/values.preview.template.yaml
=> CIV-15377 - Configure Role Assignments Url 

src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/judgment_by_admission_non_divergent_spec.bpmn, src/main/resources/camunda/upload_translated_claimant_intention_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantIntentionDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-15995
claimant_response_cui.bpmn:
upload_translated_claimant_intention_document_notify.bpmn
```
[ ] Yes
[ ] No
```
=> CIV-15995 JbA Live Feed LipvLip

src/main/resources/camunda/initiate_cosc_application_after_payment.bpmn, src/main/resources/camunda/process_cosc_application.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateCoSCApplicationAfterPaymentTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ProcessCoscApplicationTest.java
https://tools.hmcts.net/jira/browse/CIV-15759
https://tools.hmcts.net/jira/browse/CIV-15760
https://tools.hmcts.net/jira/browse/CIV-15761
https://tools.hmcts.net/jira/browse/CIV-16208
old pr: https://github.com/hmcts/civil-camunda-bpmn-definition/pull/1156 AND https://github.com/hmcts/civil-camunda-bpmn-definition/pull/1151
old test pr: https://github.com/hmcts/civil-citizen-ui/pull/5159
Add new rpa event: 600 COSC
```
[ ] Yes
[ ] No
```
=> CIV-15759 And CIV-15761: Add new rpa event: 600 COSC & CRON Job triggers 600 Event Code

src/main/resources/camunda/confirm_order_review.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ConfirmOrderReviewTest.java
https://tools.hmcts.net/jira/browse/CIV-15612
```
[ ] Yes
[ x ] No
```
=> CIV-15612 Confirm order review

bin/utils/process-definition.sh, src/main/resources/camunda/settle_claim_paid_in_full_notification.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/SettleClaimPaidInFullNotificationTest.java
https://tools.hmcts.net/jira/browse/CIV-16291
```
[ ] Yes
[ ] No
```
=> CIV-16291 Notify defendant Lip - marked as paid in full

src/main/resources/camunda/apply_noc_decision_defendant_lip.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionDefendantLipTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java
https://tools.hmcts.net/jira/browse/CIV-15959
```
[ ] Yes
[x] No
```
=> CIV-15959 - Defendant Notice of Change submission - Check case state

src/main/resources/camunda/defendant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-15998
Updated the  LR defendant response flow for LiP v LR claim.
```
[ ] Yes
[x] No
```
=> CIV-15998 - Check defendant LR response upon submission of defendant response to claimant LiP

src/main/resources/camunda/court_officer_order.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CourtOfficerOrderTest.java
https://tools.hmcts.net/jira/browse/CIV-15640
```
[ ] Yes
[x] No
```
=> CIV-15640 add new camunda Court Officer Order

src/main/resources/camunda/confirm_order_review_final_order.bpmn, src/main/resources/camunda/set_aside_judgment_request.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/SetAsideJudgmentTest.java
https://tools.hmcts.net/jira/browse/CIV-15871
```
[ ] Yes
[ x ] No
```
=> CIV-15871 Confirm order review update tasklist

src/main/resources/camunda/trial_ready_check.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TrialReadyCheckTest.java
https://tools.hmcts.net/jira/browse/CIV-15723
Trial ready check closes dashboard for trial arrangements journey
```
[ ] Yes
[x] No
```
=> CIV-15723 - trial ready check bpmn

src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/upload_translated_claimant_intention_document_notify.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedClaimantIntentionDocumentTest.java
https://tools.hmcts.net/jira/browse/CIV-15750
```
[ ] Yes
[X ] No
```
=> CIV-15750 Generate JBA docs for LIP Def/Claimant docs

src/main/resources/camunda/claimant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/CIV-15753
```
[ ] Yes
[ ] No
```
=> CIV-15753 Judgment by Admission - modify Submission screen

charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml, src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
https://tools.hmcts.net/jira/browse/CIV-16322
Work allocation task for caseworker to take case offline when CML of GA is updated
```
[ ] Yes
[x ] No
```
=> CIV-16322 added ga location update to CUI claimant response journey

src/main/resources/camunda/defendant_response.bpmn, src/main/resources/camunda/defendant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseSpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseTest.java
https://tools.hmcts.net/jira/browse/CIV-16413
Generate DQ for non-full admit only
```
[ ] Yes
[x] No
```
=> CIV-16413 Generate DQ for non-full admit only

src/main/resources/camunda/apply_noc_decision.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ApplyNocDecisionTest.java
defendant lip noc email notifications
```
[ ] Yes
[ ] No
```
=> CIV-15960 defendant lip noc email notifications

charts/civil-camunda/values.preview.template.yaml, src/main/resources/camunda/generate_non_divergent_spec_DJ_form.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateNonDivergentSpecDJFormTest.java
https://tools.hmcts.net/jira/browse/CIV-16427
```
[ ] Yes
[X ] No
```
=> CIV-16427 Remove Sending DJ Letters to LR

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-16651
Lip vs LIP Count Calculator Accept should go to JBA
```
[ ] Yes
[X ] No
```
=> CIV-16651 Lip vs LIP Count Calculator Accept should go to JBA

charts/civil-camunda/Chart.yaml
=> DTSCCI-1691 bump chart

src/main/resources/camunda/take_case_offline.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TakeCaseOfflineTest.java
https://tools.hmcts.net/jira/browse/CIV-16911
Added a task to update claimant and applicant dashboard notification and task list when main case goes offline.
```
[ ] Yes
[x] No
```
=> CIV-16911 - Update TaskList when Take Case  offline submitted for Lip v Lip claim

src/main/resources/camunda/generate_hearing_notice.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/GenerateHearingNoticeTest.java
https://tools.hmcts.net/jira/browse/CIV-16804
```
[ ] Yes
[ x ] No
```
=> CIV-16804 allow Lip v LR claims bulk print

src/main/resources/camunda/apply_noc_decision_defendant_lip.bpmn
=> DTSCCI-000 reflect correct process name

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-17037
Added new role to access profile.
```
[ ] Yes
[x] No
```
=> CIV-17037 - Pre-requisite changes for work allocating to WLU

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-17040
Do not generate DQ if full defence not proceed
```
[ ] Yes
[x] No
```
=> CIV-17040 Do not generate DQ if full defence not proceed

src/main/resources/camunda/create_sdo.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateSDOTest.java
https://tools.hmcts.net/jira/browse/CIV-16832
Pause SDO notifications etc. when bilingual party
```
[ ] Yes
[x] No
```
=> CIV-16832 Pause SDO notifications etc. when bilingual party

src/main/resources/camunda/notify_lip_reset_pin.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/NotifyLipResetPinTest.java
https://tools.hmcts.net/jira/browse/CIV-15925
```
[ ] Yes
[ ] No
```
=> CIV-15925  Reset PIN Event trigger Lip notify email

src/main/resources/camunda/create_sdo.bpmn, src/main/resources/camunda/upload_translated_document_sdo.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateSDOTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedDocumentSDOTest.java
https://tools.hmcts.net/jira/browse/CIV-16856
Add flow for uploading translated SDO
```
[ ] Yes
[x] No
```
=> CIV-16856 Add flow for uploading translated SDO

src/main/resources/camunda/apply_noc_decision_defendant_lip.bpmn, src/main/resources/camunda/claimant_response_cui.bpmn, src/main/resources/camunda/defendant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/BpmnBaseTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/CIV-16888
Put check in flowgates for CUI responses to allow for English To Welsh option
```
[ ] Yes
[x] No
```
=> CIV-16888 - check for EnglishToWelsh

src/main/resources/camunda/create_sdo.bpmn, src/main/resources/camunda/defendant_sign_settlement_agreement.bpmn, src/main/resources/camunda/upload_translated_document_settlement_agreement.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedDocumentSettlementAgreementTest.java
https://tools.hmcts.net/jira/browse/CIV-16865
Pause notifications for translation of settlement agreement
```
[ ] Yes
[x] No
```
=> CIV-16865 Pause notifications for translation of settlement agreement

src/main/resources/camunda/respond_to_query.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RespondToQueryTest.java
https://tools.hmcts.net/jira/browse/CIV-16922
- add dashboard notification event
```
[ ] Yes
[ ] No
```
=> CIV-16922 Query response dashboard notification

src/main/resources/camunda/retrigger_update_location_scheduler.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/RetriggerUpdateLocationSchedulerTest.java
=> DTSCCI-1700 migrate case location epim id

Jenkinsfile_CNP, bin/run-api-tests.sh, bin/run-nightly-api-tests.sh, build.gradle
=> DTSCCI-2255 Implement Run Failed Tests on PR

Jenkinsfile_CNP
=> DTSCCI-2255 Archive Test Artifacts Always

charts/civil-camunda/Chart.yaml, charts/civil-camunda/values.aat.template.yaml, charts/civil-camunda/values.preview.template.yaml, charts/civil-camunda/values.yaml
=> DTSCCI-2265 use oci endpoint

charts/civil-camunda/values.preview.template.yaml, src/main/resources/camunda/create_claim_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2079
```
[ ] Yes
[ ] No
```
=> DTSCCI-2079 Refactor Create Claim After Payment BPMN

src/main/resources/camunda/defendant_response.bpmn, src/main/resources/camunda/defendant_response_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseSpecTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2085
Dependant on https://github.com/hmcts/civil-service/pull/6484
Before
After
=> DTSCCI-2085 Refactor Defedant response spec bpmn to use generic notify event

config/owasp/suppressions.xml, src/main/resources/camunda/defendant_response_spec.bpmn, src/main/resources/camunda/upload_translated_defendant_sealed_form.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/DefendantResponseSpecTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedSealedFormForLipVSLRTest.java, src/test/java/uk/gov/hmcts/reform/civil/bpmn/UploadTranslatedSealedFormForLipVsLrTest.java
https://tools.hmcts.net/jira/browse/CIV-17132
pause defendant response journey for lip vs lr
```
[ ] Yes
[ ] No
```
=> CIV-17132 pause in defendant response journey li p v lr

config/owasp/suppressions.xml
=> CIV-0000 supress  CVE-2024-38808

Jenkinsfile_CNP, bin/run-api-tests.sh, build.gradle
=> DTSCCI-2334 Make Run Failed Tests Permanent In PR And Master

src/main/resources/camunda/take_case_offline.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/TakeCaseOfflineTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2281
```
[ ] Yes
[ ] No
```
=> DTSCCI-2281 Refactor Take Case Offline

src/main/resources/camunda/claimant_response_cui.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2177
BEFORE:
AFTER:
```
[ ] Yes
[ ] No
```
=> DTSCCI-2177 - Notification Refactor Claimant Response CUI

src/main/resources/camunda/case_proceeds_in_caseman.bpmn, src/main/resources/camunda/case_proceeds_in_caseman_spec.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CaseProceedsInCasemanTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-1845
Refactor case proceeds in caseman to notify all parties in same event
Depends on https://github.com/hmcts/civil-service/pull/6480
```
[ ] Yes
[ ] No
```
=> DTSCCI-1845 Refactor case proceeds in caseman to notify all parties in same event

src/main/resources/camunda/create_claim_spec_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/CreateClaimSpecAfterPaymentTest.java
https://tools.hmcts.net/jira/browse/CIV-17355
Add task for removing payment notification
```
[ ] Yes
[x] No
```
=> CIV-17355 Add task for removing payment notification

src/main/resources/camunda/migrate_cases_scheduler.bpmn
[DTSCCI-2278](https://tools.hmcts.net/jira/browse/DTSCCI-2278)
Migrate Cases config
=> DTSCCI-2278 Migrate Cases bpm

src/main/resources/camunda/judgement_paid_in_full.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/JudgementPaidInFullTest.java
https://tools.hmcts.net/jira/browse/CIV-17540
```
[ ] Yes
[ x ] No
```
=> CIV-17540 add rpa judgment paid in full

src/main/resources/camunda/initiate_general_application_after_payment.bpmn, src/test/java/uk/gov/hmcts/reform/civil/bpmn/InitiateGeneralApplicationAfterPaymentForWelshTest.java
https://tools.hmcts.net/jira/browse/CIV-17107
Added a camunda task to delete payment Dashboard notification when application is paused for translation.
```
[ ] Yes
[x] No
```
=> CIV-17107 - Delete notifications regarding awaiting payment when application is paused

.github/workflows/validate.yml
https://tools.hmcts.net/jira/browse/DTSCCI-2716
fix ttl check
```
[ ] Yes
[ ] No
```
=> DTSCCI-2716 fix ttl check

.github/renovate.json
=> DTSCCI-0000 Update renovate.json
